title = 'config'

# # files paths
# #home_dir = '/home/emc-brid'  # glx
# home_dir = '/Users/emcbride' # personal ordi
# # home_dir = '/jet/home' # bridges2
# #
# data_dir = '/Users/emcbride/Datasets/LoReLi'
# # data_dir = '/data/cluster/emc-brid/Datasets/LoReLi'

sim_dir = 'ps_ee'
Pee_dir = 'spectra/Pee'
kSZ_dir = 'spectra/kSZ'
fits_dir = 'lklhd_files'
params_dir = 'param_files'

ion_fn = 'metadata/ion_histories_full.npz'
redshift_fn = 'metadata/redshift_list.dat'

# data config
survey = false
lmin = 1500
lmax = 10000
addnoise = false
use_data = true
sn = '12958'

# emulator
load_emulator = true
nndir = 'setrandomseed3'
emu = 'setrandomseed3/emuv5.0_run0'

# mcmc
nwalkers = 12
burnin = 1000
nsteps = 10000
rescale_cov = 0.1
add2d = true
addPlanck = false
vectorize = true

# parameters
which_params_to_fit = ['tau', 'Mmin', 'fesc'] # ['fX', 'rHS', 'tau', 'Mmin', 'fesc']
Planck = 0.0576 #  0.054
Planck_err = 0.0060 # 0.007
